services:
  postgres:
    image: postgres:15-alpine
    container_name: gamification-postgres
    environment:
      POSTGRES_DB: gamification
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      # This script will create a second DB for sonar
      POSTGRES_MULTIPLE_DATABASES: gamification,sonarqube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gamification"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: gamification-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gamification-frontend
    ports:
      - "4200:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: gamification-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin123
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: gamification-scanner
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=sqp_695098f1ebda5a05c926aef78fa61fcd69bd236b
    volumes:
      - .:/usr/src
    depends_on:
      - sonarqube
    profiles:
      - scan

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs: