sonar.projectKey=gamification-platform
sonar.projectName=Gamification Platform
sonar.host.url=http://sonarqube:9000

# Frontend
sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=**/pages/**,**/components/**,**/guards/**,**/interceptors/**,**/models/**,**/environments/**

# Backend
sonar.java.binaries=backend/target/classes
sonar.java.source=17