spring.application.name=gamification-backend
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gamification
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:my-gamification-app-secret-key-dev-pfe-2026-louay_abidi}
jwt.expiration=86400000

# Reduce redundant DB hits
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.open-in-view=false


spring.task.scheduling.pool.size=2