spring.application.name=gamification-backend
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gamification
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:my-secret-jwt-key-for-development-and-testing}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Reduce redundant DB hits
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.open-in-view=false
spring.task.scheduling.pool.size=2

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Frontend URL
app.frontend-url=http://localhost:4200
app.upload-dir=uploads/badges
app.base-url=http://localhost:8081

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs